version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - type: volume
        source: mydata
        target: /mydata
      - type: volume
        source: geoipupdate
        target: /usr/share/GeoIP
  # storage:
  #   image: ubuntu:20.04
  #   volumes:
  #     - type: volume
  #       source: mydata
  #       target: /mydata
volumes:
  mydata:
  geoipupdate:
